### ISSUE TITLE
Front page links don't take account of Moodle root

### ISSUE THREAD

**Issue by richardjonesnz** [kennibc/moodle-theme_fordson#2]
Hi Chris

Great theme, I'm studying it intensely but you've done so much with Boost already.  

I installed it on a local text site but I noticed that since I have my site installed at /localhost/moodle/ the front page links then expect moodle to be at the root because of the leading slash, as in /my/ or /calendar.view.php and so on.

I haven't been able to track down where that happens but will let you know if I find out.

Cheers
Richard Jones

**Comment by richardjonesnz** [comment]
Just seen the setting in the Special Course Creator Section - sorry!

**Comment by kennibc** [comment]
Good to hear you got it solved.

**Comment by kennibc** [comment]
Just an FYI for anyone else that experiences this.  The Icon Navigation in Fordson has default links for the first 4 icons that are based off Moodle being in the root of your server.  If you install Moodle in a sub-directory such as  www.mysite.com/moodle/    then you must edit the Icon Navigation to reflect the sub-directory.  
![moodle 3 2 sandbox administration appearance themes fordson](https://cloud.githubusercontent.com/assets/1692748/23108997/b0278e1e-f6e2-11e6-81b4-1d4045b6b1b5.png)
