### ISSUE TITLE
Log in link in the header, contrast too low

### ISSUE THREAD

**Issue by mudrd8mz** [kennibc/moodle-theme_fordson#3]
![image](https://cloud.githubusercontent.com/assets/85831/22697512/eabda5ee-ed51-11e6-92bb-d66697765179.png)

**Comment by kennibc** [comment]
I think I can fix that by adjusting the color
.usermenu {
    color: #fff;
}

I'll add it in.

**Comment by kennibc** [comment]
Fixed.  I am now using the $navbarurl variable with this text and the preset is set at #fff in the new version.  Will publish soon.  Waiting on your other findings.

**Comment by kennibc** [comment]
Fixed in v1.2.0
Made both text and links the same color in preset: #fffff
