### ISSUE TITLE
The "This Course" dropdown vertical alignment

### ISSUE THREAD

**Issue by mudrd8mz** [kennibc/moodle-theme_fordson#4]
The dropdown button "This Course" does not align nicelyvertically with the navbar:

![image](https://cloud.githubusercontent.com/assets/85831/22697903/32c5427e-ed53-11e6-956d-f098252e5ac2.png)

**Comment by kennibc** [comment]
Do you have a browser and OS so I can check?  I don't see this on my dev site.  Ubuntu 16 chrome & firefox latest.

**Comment by kennibc** [comment]
Can you completely clear and purge all caches?  I cannot replicate this issue.

**Comment by mudrd8mz** [comment]
Hmm, so I assume this is not how it looks for you, too:

![screenshot_2017-02-07_18-06-44](https://cloud.githubusercontent.com/assets/85831/22702207/3551ed64-ed60-11e6-9a1e-760cf00705b1.png)

**Comment by mudrd8mz** [comment]
It is after hard reload and purged cached, Linux Chrome 55.0.2883.87 (64-bit)

**Comment by mudrd8mz** [comment]
Same with Firefox 50.1.0

**Comment by kennibc** [comment]
found the issue.  Seems there was a CSS entry for the breadcrumb button to float:right.  This got removed in the very latest 3.2.1 and I added it back to Fordson SCSS file.  I will publish the v1.2.0 version and it should fix it.
