### ISSUE TITLE
Non-default presets are often unusable

### ISSUE THREAD

**Issue by mudrd8mz** [kennibc/moodle-theme_fordson#5]
The default preset looks good. But others have often various issues - varying from purely aesthetic to actually usability issues - for example the Darkly actually hides the content from the user:

![image](https://cloud.githubusercontent.com/assets/85831/22698415/ca8a795c-ed54-11e6-8dab-279bfd0f0eb5.png)

**Comment by mudrd8mz** [comment]
This is not the first and only theme with these issues. I have actually found Boostwach presets not really suitable for Moodle, to be honest. It will be interesting to see if it is a vital idea. I personally tend to the "do one thing and do it well" approach.

**Comment by kennibc** [comment]
I've noticed the same. It is related to the color chooser page.  If you use one of the other presets you must clear the settings on the color chooser page as these override the preset and lead to issues.  

I will upload a new release without any presets.  In future releases I want to handcraft presets with "purpose" such as elementary schools, secondary, colleges, business, etc.

**Comment by kennibc** [comment]
Fixed.  Removed all presets from v1.2.0.
Updated plugin documentation too.
