### ISSUE TITLE
Messages Drop down's row issue on RTL

### ISSUE THREAD

**Issue by Dadparvar** [kennibc/moodle-theme_fordson#6]
Hi Chris, 

We are using RTL and I saw a problem in rows in message box drop down, that each row was getting all the height of the drop down. I just fixed it with this:
`.popover-region-messages .content-item {
    height: inherit !important;
}`

**Comment by kennibc** [comment]
Ok.  I will try dropping this into the styles.php.  I wonder if it is related to boost or just Fordson?

**Comment by Dadparvar** [comment]
Just checked it in Boost, and didn't see the same problem. Seems to be related to just Fordson in my case.

**Comment by kennibc** [comment]
Do you have a screenshot.  When I look at messages with AR as my language things look fine to me.  I am not seeing the issue that this fixes.

**Comment by Dadparvar** [comment]
Sure. I attached a gif to show you.
To reproduce it, Use RTL (such as Persian) and then in this page click to open the messages:
admin/settings.php?section=themesettingfordson
![fordson-bug1](https://cloud.githubusercontent.com/assets/7770842/23134146/9325994e-f748-11e6-9364-785bebfe8184.gif)

**Comment by kennibc** [comment]
This is what I see when doing switching to AR and messages.
![moodle lang](https://cloud.githubusercontent.com/assets/1692748/23134559/4483987a-f763-11e6-9ef6-075c2577bfe8.png)

**Comment by kennibc** [comment]
Even on the settings admin page I am getting a normal appearance.  
![moodle fordson](https://cloud.githubusercontent.com/assets/1692748/23138460/96fcbe3a-f775-11e6-9293-5fe6bbf11370.png)

**Comment by Dadparvar** [comment]
Weird. Maybe there was something wrong in my side. (Still when I remove that part of code, I face with the same problem)

Anyway, thanks for the great work, and your attention.
