### ISSUE TITLE
Add strings to frontpage buttons

### ISSUE THREAD

**Issue by nadavkav** [kennibc/moodle-theme_fordson#7]
Hi Chris,
Please see if you can add translation tokens to the front page special buttons: Dashboard, Calendar, Badges...
As I would like to translate those buttons.

Kindly,
Nadav

**Comment by kennibc** [comment]
Sounds like a good idea.  I'll mark this closed once I put the strings in for default setting page.

**Comment by nadavkav** [comment]
Great :smile: 
Should I send a PR?

**Comment by kennibc** [comment]
I am not sure how Moodle handles the translations.  Version 1.2.5 of Fordson will have these new icon text strings for the buttons.

**Comment by kennibc** [comment]
Version 1.2.5 is posted in the plugin directory.  Please let me know if there is anything else that needs a lang string.

**Comment by nadavkav** [comment]
Looks great. thanks :smile:
